export const siteConfig = {
  businessName: "BVS REAL ESTATE",
  shortName: "BVS Real Estate",
  contactPerson: "Banumathi B",
  phone: "9750176664",
  phoneFormatted: "+91 97501 76664",
  whatsapp: "9750176664",
  whatsappUrl: "https://wa.me/919750176664",
  email: "[EMAIL TO BE PROVIDED]",
  workingHours: "Mon - Sat: 9:00 AM - 7:30 PM",
  address: {
    street: "Anjugam 2nd Street",
    landmark: "Near Aavin Palpannai",
    locality: "East Govindapuram",
    city: "Dindigul",
    pincode: "624001",
    state: "Tamil Nadu",
    country: "India",
    full: "Anjugam 2nd Street, Near Aavin Palpannai, East Govindapuram, Dindigul - 01, Tamil Nadu, India",
  },
  taglineTamil: "இடம் • வீடு • தொழில் • கோட்டில் • விவசாயம் வாங்க விற்க",
  taglineEnglish: "Buy & Sell Lands, Houses, Commercial Sites, Sheds & Agricultural Lands",
  heroHeading: "Find the Right Place for Your Future",
  heroSubheading: "Explore lands and properties in and around Dindigul with BVS Real Estate.",
  googleMapsUrl: "https://maps.google.com/?q=East+Govindapuram+Dindigul+Tamil+Nadu+India",
  serviceAreas: [
    "Dindigul City",
    "East Govindapuram",
    "Palani Road",
    "Chettinaickenpatti",
    "Near Aavin Palpannai",
    "Batlagundu Road",
    "Natham Road",
    "Vadamadurai Bypass",
  ],
  trustStats: [
    { label: "Direct Owner Deals", value: "100%" },
    { label: "Document Verification", value: "Verified" },
    { label: "Local Dindigul Focus", value: "Specialist" },
    { label: "Customer Enquiries", value: "Direct" },
  ],
  navLinks: [
    { label: "Home", href: "/" },
    { label: "Properties", href: "/properties" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  propertyTypes: [
    { id: "LAND", label: "Land", description: "Prime plots and open lands ready for development" },
    { id: "HOUSE", label: "House", description: "Independent houses, villas and residential living" },
    { id: "RESIDENTIAL PLOT", label: "Residential Plot", description: "Approved layout plots for custom homes" },
    { id: "AGRICULTURAL LAND", label: "Agricultural Land", description: "Fertile farm lands, coconut groves and garden lands" },
    { id: "COMMERCIAL PROPERTY", label: "Commercial Property", description: "Main road sites, shops, godowns and business spaces" },
  ] as const,
  propertyStatuses: ["AVAILABLE", "RESERVED", "SOLD"] as const,
};

export type PropertyType = (typeof siteConfig.propertyTypes)[number]["id"];
export type PropertyStatus = (typeof siteConfig.propertyStatuses)[number];
